REGION_NAME = "us-east-1"
SECURITY_GROUP_ID = ["sg-01f6eae0a86996c66"]
# APP_TIER_AMI = "ami-052a117fb5b2b83d0_old"
INSTANCE_TYPE = 't2.micro'
AWS_S3_INPUT_BUCKET_NAME = "cse-546-input-bucket-adk"
AWS_S3_OUTPUT_BUCKET_NAME = "cse-546-output-bucket-adk"
AWS_SQS_REQUEST_QUEUE_NAME = "cse-546-request-queue"
AWS_SQS_RESPONSE_QUEUE_NAME = "cse-546-response-queue"
AWS_ACCESS_KEY_ID = "AKIA4WWZEBOIZLDVCCTD"
AWS_ACCESS_KEY_SECRET = "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"